version: '3.7'

services:
  web:
    build: ./app
    user: root
    command: "/usr/local/bin/jupyter lab --ip=0.0.0.0 --port 8888 --allow-root" 
    volumes:
      - /home/share:/app
    ports:
      - 8888:8888
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 8080:8080
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
